FROM ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive


RUN apt-get update && \
    apt-get install -y apache2 mysql-server php libapache2-mod-php php-mysql phpmyadmin


WORKDIR /var/www/html

ADD app /var/www/html/


RUN ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin

RUN echo 'Include /etc/phpmyadmin/apache.conf' >> /etc/apache2/apache2.conf


RUN sed -i 's/DirectoryIndex index.html/DirectoryIndex index.php index.html/g' /etc/apache2/mods-enabled/dir.conf && \
    echo 'RewriteEngine On' >> /var/www/html/.htaccess && \
    echo 'RewriteRule ^$ index.php [L]' >> /var/www/html/.htaccess


CMD service apache2 start && service mysql start && tail -f /dev/null
